# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Psylinkable extends Resource

@export var requiredFocus: String
@export var linkSound: String
@export var enoughPlantsLetterLabel: String
@export var enoughPlantsLetterText: String
