# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Interactable extends Resource

@export var compClass: String
@export var activeTicks: Int
@export var cooldownTicks: Int
@export var jobString: String
@export var onCooldownString: String
@export var cooldownFleck: String
@export var cooldownFleckSpawnIntervalTicks: Int
@export var cooldownFleckScale: Float
@export var activateTexPath: String
@export var soundActivate: String
@export var ticksToActivate: Int
@export var cooldownPreventsRefuel: String
