# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_ShipLandingBeacon extends Resource

@export var edgeLengthRange: String
@export var landingAreaTerrainSupport: String
