# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_TemperatureRuinable extends Resource

@export var minSafeTemperature: Int
@export var maxSafeTemperature: Int
@export var progressPerDegreePerTick: Float
