# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_RitualHediffGiverInRoom extends Resource

@export var hediff: String
@export var resetLastRecreationalDrugTick: String
@export var minRadius: Int
@export var severity: Float
