# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_TreeConnection extends Resource

@export var pawnKind: String
@export var spawnDays: Int
@export var initialConnectionStrengthRange: String
@export var connectionStrengthLossPerDryadDeath: Float
@export var connectionStrengthGainPerHourPruningBase: Float
@export var spawningPodOffset: String
@export var spawningPodSizeRange: String
@export var maxDryadsWild: Int
