# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_RitualEffectIntervalSpawnCircle extends Resource

@export var fleckDef: String
@export var area: String
@export var radius: Int
@export var concentration: Int
@export var spawnIntervalTicks: Int
@export var spawnCount: Int
@export var rotation: String
@export var scalePositionWithRoom: String
@export var onlySpawnInSameRoom: String
