# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_RitualEffectSpawnOnRole extends Resource

@export var effecterDef: String
@export var roleId: String
@export var maxBursts: Int
@export var delay: Int
