# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_CausesGameCondition_ClimateAdjuster extends Resource

@export var conditionDef: String
@export var worldRange: Int
@export var preventConditionStacking: String
