# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_CausesGameCondition extends Resource

@export var conditionDef: String
@export var worldRange: Int
@export var compClass: String
@export var preventConditionStacking: String
