# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_TerrainPumpDry extends Resource

@export var soundWorking: String
@export var radius: Float
@export var daysToRadius: Int
