# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityWallraise extends Resource

@export var compClass: String
@export var screenShakeIntensity: Float
@export var clamorType: String
@export var clamorRadius: Int
@export var sound: String
