# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_RitualEffectDrum extends Resource

@export var fleckDef: String
@export var maxDistance: Int
@export var spawnIntervalTicks: Int
@export var spawnCount: Int
@export var maxOffset: Float
