# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Book extends Resource

@export var nameMaker: String
@export var descriptionMaker: String
@export var ageYearsRange: String
