# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_HoldingPlatformTarget extends Resource

@export var baseEscapeIntervalMtbDays: Int
@export var getsColdContainmentBonus: String
