# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Art extends Resource

@export var nameMaker: String
@export var descriptionMaker: String
@export var canBeEnjoyedAsArt: String
@export var minQualityForArtistic: String
@export var mustBeFullGrave: String
