# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_RitualEffectIntervalSpawnDividedCircle extends Resource

@export var radius: Float
@export var numCopies: Int
@export var offset: String
@export var roomCheckOffset: String
@export var effecterDef: String
@export var scalePositionWithRoom: String
@export var onlySpawnInSameRoom: String
