# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_FleckEmitter extends Resource

@export var fleck: String
@export var emissionInterval: Int
@export var soundOnEmission: String
@export var saveKeysPrefix: String
