# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityEffectWithDuration extends Resource

@export var compClass: String
@export var durationMultiplier: String
@export var psychic: String
@export var goodwillImpact: Int
