# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_RitualEffectStaticAreaRandomMote extends Resource

@export var area: String
@export var spawnCount: Int
@export var minDist: Int
@export var scalePositionWithRoom: String
@export var onlySpawnInSameRoom: String
