# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityReassure extends Resource

@export var successMessage: String
@export var baseCertaintyGain: Float
@export var sound: String
