# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_MoteEmitterRandomColor extends Resource

@export var saveKeysPrefix: String
@export var mote: String
@export var emissionInterval: Int
@export var ticksSinceLastEmittedMaxOffset: Int
