# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AssignableToPawn extends Resource

@export var drawAssignmentOverlay: String
@export var compClass: String
@export var noAssignablePawnsDesc: String
@export var drawUnownedAssignmentOverlay: String
