# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityFleckOnTarget extends Resource

@export var fleckDef: String
@export var scale: Float
@export var sound: String
@export var preCastTicks: Int
