# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityConvert extends Resource

@export var successMessage: String
@export var failMessage: String
@export var failedThoughtInitiator: String
@export var failedThoughtRecipient: String
@export var convertPowerFactor: Int
@export var sound: String
