# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_SpawnerPawn extends Resource

@export var lordJob: String
@export var spawnSound: String
@export var initialPawnsPoints: Int
@export var maxSpawnedPawnsPoints: Int
@export var lordJoinRadius: Int
@export var chooseSingleTypeToSpawn: String
@export var spawnMessageKey: String
@export var pawnsLeftToSpawnKey: String
@export var noPawnsLeftToSpawnKey: String
@export var nextSpawnInspectStringKey: String
@export var nextSpawnInspectStringKeyDormant: String
@export var maxPawnsToSpawn: Int
@export var showNextSpawnInInspect: String
@export var pawnSpawnIntervalDays: Int
@export var shouldJoinParentLord: String
