# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Facility extends Resource

@export var maxSimultaneous: Int
@export var mustBePlacedAdjacentCardinalToBedHead: String
@export var maxDistance: Int
@export var mustBePlacedAdjacent: String
@export var mustBePlacedAdjacentCardinalToAndFacingBedHead: String
