# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityNeuroquake extends Resource

@export var goodwillImpactForBerserk: Int
@export var goodwillImpactForNeuroquake: Int
@export var worldRangeTiles: Int
@export var screenShakeIntensity: Int
@export var mentalStateRadius: Int
