# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_CanBeDormant extends Resource

@export var compClass: String
@export var startsDormant: String
@export var canWakeUpFogged: String
@export var wakeUpDelayRange: Int
@export var wakeUpEffect: String
@export var maxDistAwakenByOther: Int
@export var wakeUpRepeatSignalDelayRange: String
@export var delayedWakeUpDoesZs: String
@export var showSleepingZs: String
@export var wakeUpDelayStateLabelKey: String
@export var awakeStateLabelKey: String
@export var dormantStateLabelKey: String
