# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_EggLayer extends Resource

@export var eggUnfertilizedDef: String
@export var eggFertilizedDef: String
@export var eggFertilizationCountMax: Int
@export var eggLayIntervalDays: Float
@export var eggProgressUnfertilizedMax: Float
@export var eggCountRange: Int
