# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Ingredients extends Resource

@export var splitTransferableFoodKind: String
@export var noIngredientsFoodKind: String
@export var performMergeCompatibilityChecks: String
