# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityCounsel extends Resource

@export var successMessage: String
@export var successMessageNoNegativeThought: String
@export var failMessage: String
@export var failedThoughtRecipient: String
@export var sound: String
