# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Battery extends Resource

@export var storedEnergyMax: Int
@export var efficiency: Float
@export var shortCircuitInRain: String
@export var transmitsPower: String
