# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Refuelable extends Resource

@export var fuelConsumptionRate: Float
@export var fuelCapacity: Float
@export var fuelConsumptionPerTickInRain: Float
@export var initialFuelPercent: Int
@export var showAllowAutoRefuelToggle: String
@export var functionsInVacuum: String
@export var targetFuelLevelConfigurable: String
@export var initialConfigurableTargetFuelLevel: Int
@export var consumeFuelOnlyWhenUsed: String
@export var autoRefuelPercent: Float
@export var showFuelGizmo: String
@export var drawOutOfFuelOverlay: String
@export var drawFuelGaugeInMap: String
@export var canEjectFuel: String
@export var fuelLabel: String
@export var fuelGizmoLabel: String
@export var outOfFuelMessage: String
@export var fuelMultiplier: Float
@export var minimumFueledThreshold: Int
@export var factorByDifficulty: String
@export var fuelIconPath: String
@export var fuelIsMortarBarrel: String
@export var initialAllowAutoRefuel: String
@export var consumeFuelOnlyWhenPowered: String
