# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Stunnable extends Resource

@export var useLargeEMPEffecter: String
@export var empEffecterDimensions: String
@export var empEffecterOffset: String
@export var empChancePerTick: Float
