# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Milkable extends Resource

@export var milkDef: String
@export var milkIntervalDays: Int
@export var milkAmount: Int
@export var milkFemaleOnly: String
