# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_DamageOnInterval extends Resource

@export var damageDef: String
@export var damage: Int
@export var ticksBetweenDamage: Int
