# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Drug extends Resource

@export var chemical: String
@export var addictiveness: Float
@export var minToleranceToAddict: Float
@export var existingAddictionSeverityOffset: Float
@export var needLevelOffset: Float
@export var listOrder: Int
@export var isCombatEnhancingDrug: String
@export var overdoseSeverityOffset: String
@export var largeOverdoseChance: Float
