# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Targetable extends Resource

@export var compClass: String
@export var psychicSensitiveTargetsOnly: String
@export var doCameraShake: String
@export var fleckOnTarget: String
@export var fleckOnUsed: String
@export var fleckOnUsedScale: Int
@export var ignorePlayerFactionPawns: String
@export var fleshCorpsesOnly: String
@export var nonDessicatedCorpsesOnly: String
