# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_HeatPusher extends Resource

@export var compClass: String
@export var heatPerSecond: Float
@export var heatPushMaxTemperature: Int
@export var heatPushMinTemperature: Int
