# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityStopMentalState extends Resource

@export var psyfocusCostForMinor: Float
@export var psyfocusCostForMajor: Float
@export var psyfocusCostForExtreme: Float
