# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilitySmokepop extends Resource

@export var smokeRadius: Float
@export var clamorType: String
@export var clamorRadius: Int
