# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_ThingContainer extends Resource

@export var compClass: String
@export var stackLimit: Int
@export var minCountToEmpty: Int
@export var drawStackLabel: String
@export var containedThingOffset: String
