# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_SpawnSubplant extends Resource

@export var compClass: String
@export var subplant: String
@export var maxRadius: Float
@export var dontWipePlant: String
@export var saveKeysPrefix: String
@export var maxPlants: Int
@export var subplantSpawnDays: Int
@export var minGrowthForSpawn: Float
@export var initialGrowthRange: String
@export var canSpawnOverPlayerSownPlants: String
@export var spawnSound: String
