# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Useable_CallBossgroup extends Resource

@export var bossgroupDef: String
@export var spawnLetterLabelKey: String
@export var spawnLetterTextKey: String
@export var effecterDef: String
@export var delayTicks: Int
