# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Spawner extends Resource

@export var thingToSpawn: String
@export var spawnCount: Int
@export var spawnIntervalRange: Int
@export var spawnMaxAdjacent: Int
@export var spawnForbidden: String
@export var saveKeysPrefix: String
@export var inheritFaction: String
@export var requiresPower: String
@export var writeTimeLeftToSpawn: String
@export var showMessageIfOwned: String
