# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_PlantDamager extends Resource

@export var ticksBetweenDamage: Int
@export var radius: Int
@export var damagePerCycle: Int
@export var cycleCountOnSpawn: Int
