# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_UseEffectInstallImplant extends Resource

@export var hediffDef: String
@export var bodyPart: String
@export var canUpgrade: String
