# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityWordOfLove extends Resource

@export var destination: String
@export var psychic: String
@export var applicableToMechs: String
