# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_WakeUpDormant extends Resource

@export var wakeUpSound: String
@export var wakeUpIfAnyTargetClose: String
@export var wakeUpCheckRadius: Float
@export var wakeUpOnThingConstructedRadius: Float
@export var wakeUpWithDelay: String
@export var radiusCheckInspectPaneKey: String
@export var activateMessageKey: String
@export var activatePluralMessageKey: String
@export var wakeUpOnDamage: String
@export var onlySendSignalOnce: String
