# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityGiveHediff extends Resource

@export var compClass: String
@export var hediffDef: String
@export var onlyBrain: String
@export var applicableToMechs: String
@export var canTargetBaby: String
@export var onlyApplyToSelf: String
@export var replaceExisting: String
@export var sound: String
@export var durationMultiplier: String
@export var psychic: String
@export var goodwillImpact: Int
@export var applyGoodwillImpactToLodgers: String
