# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityEffecterOnTarget extends Resource

@export var effecterDef: String
@export var maintainForTicks: Int
@export var scale: Float
