# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_RitualEffectIntervalSpawnArea extends Resource

@export var fleckDef: String
@export var area: String
@export var spawnIntervalTicks: Int
@export var spawnCount: Int
@export var scalePositionWithRoom: String
@export var onlySpawnInSameRoom: String
@export var rotation: String
@export var scale: String
@export var offset: String
@export var velocityDir: String
@export var velocity: String
@export var rotationRate: Int
