# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Glower extends Resource

@export var glowRadius: Float
@export var glowColor: String
@export var colorPickerEnabled: String
@export var darklightToggle: String
@export var overlightRadius: Float
