# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_CausesGameCondition_PsychicEmanation extends Resource

@export var conditionDef: String
@export var compClass: String
@export var worldRange: Int
@export var droneLevelIncreaseInterval: Int
@export var droneLevel: Int
@export var preventConditionStacking: String
