# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Hibernatable extends Resource

@export var incidentTargetWhileStarting: String
@export var sustainerActive: String
