# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityStartTrial extends Resource

@export var ritualDef: String
@export var ritualDefForPrisoner: String
@export var ritualDefForMentalState: String
@export var targetRoleId: String
