# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityGiveMentalState extends Resource

@export var compClass: String
@export var stateDef: String
@export var soundMale: String
@export var soundFemale: String
@export var stateDefForMechs: String
@export var psychic: String
@export var durationMultiplier: String
@export var canTargetBosses: String
@export var goodwillImpact: Int
