# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_ProjectileInterceptor extends Resource

@export var radius: Float
@export var interceptGroundProjectiles: String
@export var interceptNonHostileProjectiles: String
@export var interceptOutgoingProjectiles: String
@export var color: String
@export var idlePulseSpeed: Int
@export var minIdleAlpha: Float
@export var disarmedByEmpForTicks: Int
@export var activeSound: String
@export var reactivateEffect: String
@export var chargeIntervalTicks: Int
@export var chargeDurationTicks: Int
@export var interceptAirProjectiles: String
@export var minAlpha: Float
@export var interceptEffect: String
