# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_FireOverlay extends Resource

@export var fireSize: Float
@export var offset: String
@export var offsetNorth: String
@export var offsetSouth: String
@export var offsetWest: String
@export var offsetEast: String
