# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityTeleport extends Resource

@export var compClass: String
@export var destination: String
@export var randomRange: String
@export var clamorType: String
@export var clamorRadius: Int
@export var destClamorType: String
@export var destClamorRadius: Int
@export var stunTicks: String
@export var goodwillImpact: Int
@export var applyGoodwillImpactToLodgers: String
@export var requiresLineOfSight: String
@export var range: Float
