# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityChunkskip extends Resource

@export var chunkCount: Int
@export var scatterRadius: Float
@export var psychic: String
@export var clamorType: String
@export var clamorRadius: Int
