# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_SendSignalOnMotion extends Resource

@export var onlyHumanlike: String
@export var radius: Float
@export var enableAfterTicks: Int
@export var signalTag: String
