# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_MoteEmitterProximityScan extends Resource

@export var mote: String
@export var emissionInterval: Int
@export var maintain: String
@export var soundEmitting: String
@export var saveKeysPrefix: String
@export var warmupPulseFadeInTime: Float
@export var warmupPulseSolidTime: Float
@export var warmupPulseFadeOutTime: Float
