# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Hackable extends Resource

@export var defence: Int
@export var effectHacking: String
@export var notHackedInspectString: String
@export var autohackWarningString: String
@export var completedQuest: String
@export var hackingCompletedSound: String
