# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AmbientSound extends Resource

@export var sound: String
@export var disabledOnUnpowered: String
@export var disableOnHacked: String
