# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_BiosculpterPod extends Resource

@export var enterSound: String
@export var exitSound: String
@export var operatingEffecter: String
@export var readyEffecter: String
@export var selectCycleColor: String
@export var biotunedCycleSpeedFactor: Float
