# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_ThrownFleckEmitter extends Resource

@export var fleck: String
@export var offsetMin: String
@export var offsetMax: String
@export var emissionInterval: Int
@export var scale: String
@export var colorA: String
@export var colorB: String
@export var rotationRate: String
@export var velocityX: String
@export var velocityY: String
@export var burstCount: Int
