# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_OverseerSubject extends Resource

@export var needsOverseerEffect: String
@export var delayUntilFeralCheck: Int
@export var feralMtbDays: Int
@export var feralCascadeRadialDistance: Int
