# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_FadesInOut extends Resource

@export var fadeInSecs: Float
@export var fadeOutSecs: Float
@export var solidTimeSecs: Int
