# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_NeuralSupercharger extends Resource

@export var jobString: String
@export var ticksToRecharge: Int
@export var effectCharged: String
@export var chargedSoundDef: String
