# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_RitualEffectLightball extends Resource

@export var fleckDef: String
@export var radius: Int
@export var spawnIntervalTicks: Int
