# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_FireOverlayRitual extends Resource

@export var fireSize: Float
@export var offset: String
@export var finalFireSize: Float
@export var fireGrowthDurationTicks: Int
@export var minRitualProgress: Float
