# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Flickable extends Resource

@export var commandTexture: String
@export var commandLabelKey: String
@export var commandDescKey: String
