# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Studiable extends Resource

@export var frequencyTicks: Int
@export var knowledgeCategory: String
@export var anomalyKnowledge: Int
@export var requiresImprisonment: String
@export var minMonolithLevelForStudy: Int
@export var studyAmountToComplete: Int
@export var studyEnabledByDefault: String
@export var showToggleGizmo: String
