# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilitySocialInteraction extends Resource

@export var interactionDef: String
@export var canApplyToUnconscious: String
@export var canApplyToMentallyBroken: String
@export var canApplyToAsleep: String
