# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_RitualEffectSpawnOnPawn extends Resource

@export var fleckDef: String
@export var compClass: String
@export var requiredTag: String
@export var eastRotationOffset: String
@export var westRotationOffset: String
@export var northRotationOffset: String
@export var spawnIntervalTicks: Int
