# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_SmokeCloudMaker extends Resource

@export var sourceStreamEffect: String
@export var cloudRadius: Float
@export var fleckScale: Int
@export var cloudFleck: String
@export var fleckSpawnMTB: Int
