# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_DestroyAfterDelay extends Resource

@export var delayTicks: Int
@export var destroyMode: String
@export var countdownLabel: String
