# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_ApparelReloadable extends Resource

@export var maxCharges: Int
@export var ammoDef: String
@export var ammoCountToRefill: Int
@export var baseReloadTicks: Int
@export var soundReload: String
@export var hotKey: String
@export var chargeNoun: String
@export var displayGizmoWhileUndrafted: String
@export var destroyOnEmpty: String
@export var ammoCountPerCharge: Int
