# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityForceJob extends Resource

@export var compClass: String
@export var jobDef: String
@export var destination: String
@export var durationMultiplier: String
@export var psychic: String
