# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityFarskip extends Resource

@export var stunTicks: String
@export var clamorType: String
@export var clamorRadius: Int
