# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Power extends Resource

@export var compClass: String
@export var basePowerConsumption: Int
@export var shortCircuitInRain: String
@export var transmitsPower: String
@export var soundAmbientProducingPower: String
@export var idlePowerDraw: Int
@export var showPowerNeededIfOff: String
