# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Rottable extends Resource

@export var daysToRotStart: Float
@export var rotDestroys: String
@export var disableIfHatcher: String
