# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_GiveHediffSeverity extends Resource

@export var hediff: String
@export var range: Float
@export var severityPerSecond: Float
@export var drugExposure: String
@export var chemical: String
@export var allowMechs: String
