# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityWaterskip extends Resource

@export var screenShakeIntensity: Float
@export var clamorType: String
@export var clamorRadius: Int
