# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Maintainable extends Resource

@export var ticksHealthy: Int
@export var ticksNeedsMaintenance: Int
@export var damagePerTickRare: Int
