# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_SkyfallerRandomizeDirection extends Resource

@export var directionChangeInterval: String
@export var maxDeviationFromStartingAngle: Int
