# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_PawnSpawnOnWakeup extends Resource

@export var pawnSpawnRadius: Int
@export var points: Int
@export var lordJob: String
@export var shouldJoinParentLord: String
@export var mentalState: String
@export var destroyAfterSpawn: String
@export var spawnSound: String
@export var dropInPods: String
@export var spawnEffecter: String
@export var activatedMessageKey: String
