# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_RitualEffectConstantCircle extends Resource

@export var radius: Float
@export var numCopies: Int
@export var moteDef: String
@export var scalePositionWithRoom: String
@export var onlySpawnInSameRoom: String
@export var offset: String
@export var roomCheckOffset: String
@export var colorOverride: String
