# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Explosive extends Resource

@export var wickTicks: Int
@export var explosiveRadius: Float
@export var explosiveDamageType: String
@export var explodeOnKilled: String
@export var startWickHitPointsPercent: Float
@export var extraInspectStringKey: String
@export var preExplosionSpawnThingDef: String
@export var preExplosionSpawnChance: Float
@export var drawWick: String
@export var chanceNeverExplodeFromDamage: Float
@export var postExplosionSpawnThingDef: String
@export var postExplosionSpawnChance: Int
@export var postExplosionSpawnThingCount: Int
@export var applyDamageToExplosionCellsNeighbors: String
@export var explosionEffect: String
@export var explosionSound: String
@export var explosiveExpandPerFuel: Float
@export var destroyThingOnExplosionSize: Int
@export var preExplosionSpawnSingleThingDef: String
@export var postExplosionGasType: String
@export var chanceToStartFire: Float
@export var damageFalloff: String
@export var explosiveExpandPerStackcount: Float
@export var requiredDamageTypeToExplode: String
