# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_MoteEmitter extends Resource

@export var mote: String
@export var emissionInterval: Int
@export var soundOnEmission: String
@export var saveKeysPrefix: String
@export var offsetMin: String
@export var offsetMax: String
@export var maintain: String
