# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_SpawnerFilth extends Resource

@export var filthDef: String
@export var spawnCountOnSpawn: Int
@export var spawnMtbHours: Int
@export var spawnRadius: Int
