# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Shearable extends Resource

@export var woolDef: String
@export var shearIntervalDays: Int
@export var woolAmount: Int
