# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_AbilityTransferEntropy extends Resource

@export var psychic: String
@export var targetReceivesEntropy: String
@export var goodwillImpact: Int
