# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_BiosculpterPod_PleasureCycle extends Resource

@export var key: String
@export var iconPath: String
@export var durationDays: Int
@export var operatingColor: String
