# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_ThrownMoteEmitter extends Resource

@export var mote: String
@export var emissionInterval: Int
@export var offsetMin: String
@export var offsetMax: String
@export var rotationRate: String
