# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Transporter extends Resource

@export var massCapacity: Int
@export var max1PerGroup: String
@export var canChangeAssignedThingsAfterStarting: String
@export var showOverallStats: String
@export var pawnLoadedSound: String
@export var pawnExitSound: String
@export var restEffectiveness: Float
