# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_DryadCocoon extends Resource

@export var compClass: String
@export var daysToComplete: Int
@export var drawContents: String
