# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_ScannerMineralsDeep extends Resource

@export var scanSpeedStat: String
@export var scanFindMtbDays: Int
@export var scanFindGuaranteedDays: Int
@export var soundWorking: String
