# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CompProperties_Usable extends Resource

@export var compClass: String
@export var useJob: String
@export var useLabel: String
@export var showUseGizmo: String
@export var useDuration: Int
@export var floatMenuOptionPriority: String
@export var floatMenuFactionIcon: String
@export var ignoreOtherReservations: String
@export var warmupMote: String
