# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_AbilityGroupDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var cooldownTicks: Int # Type C# original: int
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ritualRoleIds: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var sendMessageOnCooldownComplete: String # Type C# original: string
