# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_AbilityDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var canUseAoeToGetTargets: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var casterMustBeCapableOfViolence: String # Type C# original: string
## Liste des composants de l'objet, définissant son comportement (ex: CompPowerTrader).
@export var comps: Array # Type C# original: Array
## Propriété de jeu non documentée sémantiquement.
@export var confirmationDialogText: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var cooldownTicksRange: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disableGizmoWhileUndrafted: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var displayGizmoWhileUndrafted: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var emissionInterval: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var emittedFleck: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var gizmoClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var groupDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var hasExternallyHandledCooldown: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hostile: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hotKey: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var iconPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var jobDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var level: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var overrideGroupCooldown: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredMemes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var sendMessageOnCooldownComplete: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showCastingProgressBar: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showGizmoOnWorldView: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showPsycastEffects: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showWhenDrafted: String # Type C# original: string
## Dictionnaire des statistiques de base de l'objet/entité.
@export var statBases: Dictionary # Type C# original: Dictionary
## Propriété de jeu non documentée sémantiquement.
@export var stunTargetWhileCasting: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var targetRequired: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var targetWorldCell: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var uiOrder: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var verbProperties: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var warmupMote: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var warmupMoteSocialSymbol: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var warmupPreEndSound: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var warmupPreEndSoundSeconds: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var warmupSound: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var warmupStartSound: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var writeCombatLog: String # Type C# original: string
