# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_BillStoreModeDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ignoreIllegalLabelCharacterConfigError: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var listOrder: String # Type C# original: string
