# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_BodyTypeDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var attachPoints: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var attachPointsDessicated: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bodyDessicatedGraphicPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bodyGraphicScale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bodyNakedGraphicPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var headOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var woundAnchors: String # Type C# original: string
