# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_BiomeDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var allowFarmingCamps: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var allowRivers: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var allowRoads: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var allowedPackAnimals: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var animalDensity: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var baseWeatherCommonalities: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var campSelectionWeight: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canAutoChoose: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canBuildBase: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var coastalBeachTerrain: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var coastalWildAnimals: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var diseaseMtbDays: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var diseases: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fishTypes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var forageability: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var foragedFood: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var generatesNaturally: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hasBedrock: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hasVirtualPlants: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var impassable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isBackgroundBiome: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var isExtremeBiome: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var isWaterBiome: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var lakeBeachTerrain: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxFishPopulation: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var movementDifficulty: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var mudTerrain: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var plantDensity: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pollutionWildAnimals: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var riverbankSizeRange: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var riverbankTerrain: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var settleWarning: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var settlementSelectionWeight: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var soundsAmbient: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var terrainPatchMakers: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var terrainsByFertility: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var texture: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var wildAnimals: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var wildAnimalsCanWanderInto: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var wildPlantRegrowDays: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var wildPlants: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var wildPlantsCareAboutLocalFertility: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
