# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_BackstoryDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var bodyTypeFemale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bodyTypeGlobal: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bodyTypeMale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disallowedTraits: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var forcedTraits: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var identifier: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ignoreIllegalLabelCharacterConfigError: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var possessions: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredWorkTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiresSpawnCategory: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var shuffleable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var skillGains: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var slot: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var spawnCategories: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var title: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var titleFemale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var titleShort: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var titleShortFemale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workDisables: String # Type C# original: string
