# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_BodyPartDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var alive: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var beautyRelated: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bleedRate: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var canBeVacuumBurnt: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canScarify: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canSuggestAmputation: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var conceptual: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var delicate: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var destroyableByDamage: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var executionPartPriority: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var forceAlwaysRemovable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var frostbiteVulnerability: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hitChanceFactors: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hitPoints: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var labelShort: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pawnGeneratorCanAmputate: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var permanentInjuryChanceFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var removeRecipeLabelOverride: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var skinCovered: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var socketed: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var solid: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var spawnThingOnRemoved: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tags: String # Type C# original: string
