# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ConceptDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var gameMode: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var helpText: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var helpTextController: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var highlightTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var needsOpportunity: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var opportunityDecays: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var priority: String # Type C# original: string
