# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_CultureDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var allowedPlaceTags: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var deityNameMaker: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var deityTypeMaker: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var festivalNameMaker: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var iconPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ideoNameMaker: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var leaderTitleMaker: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pawnNameMaker: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pawnNameMakerFemale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var preferredWeaponClasses: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var styleItemTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var thingStyleCategories: String # Type C# original: string
