# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ChemicalDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var addictionHediff: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canBinge: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var geneOverdoseChanceFactorImmune: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var geneOverdoseChanceFactorResist: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var geneToleranceBuildupFactorImmune: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var geneToleranceBuildupFactorResist: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var generateAddictionGenes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var onGeneratedAddictedEvents: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var onGeneratedAddictedToleranceChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var toleranceHediff: String # Type C# original: string
