# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ComplexLayoutDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var areaPrunePercent: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canDisconnectRooms: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var clearDoorFaction: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var corridorDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minRoomHeight: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minRoomWidth: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var rewardThingSetMakerDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var roomDefs: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var threats: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
