# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ComplexThreatDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var allowPassive: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var faction: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fallbackToRoomEnteredTrigger: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minPoints: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var postSpawnPassiveThreatFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var signalActionAmbushType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var spawnAroundComplex: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var spawnInOtherRoomChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var useDropPods: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
