# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_DesignationCategoryDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var order: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var preferredColumn: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var researchPrerequisites: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showPowerGrid: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var specialDesignatorClasses: String # Type C# original: string
