# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_DesignationDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var designateCancelable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var removeIfBuildingDespawned: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var shouldBatchDraw: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var targetType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var texturePath: String # Type C# original: string
