# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_DrugPolicyDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var allowPleasureDrugs: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var entries: String # Type C# original: string
