# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_DifficultyDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var adaptationEffectFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var adaptationGrowthRateFactorOverZero: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var allowBigThreats: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var allowCaveHives: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var allowExtremeWeatherIncidents: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var allowIntroThreats: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var allowViolentQuests: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var butcherYieldFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var colonistMoodOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var cropYieldFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var deepDrillInfestationChanceFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var difficulty: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var diseaseIntervalFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var enemyDeathOnDownedChanceFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var enemyReproductionRateFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var fishingYieldFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var foodPoisonChanceFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var isCustom: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var maintenanceCostFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var manhunterChanceOnDamageFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var minThreatPointsRangeCeiling: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var mineYieldFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var nomadicMineableResourcesFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var peacefulTemples: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var playerPawnInfectionChanceFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var predatorsHuntHumanlikes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var researchSpeedFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var scariaRotChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var studyEfficiencyFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var threatScale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tradePriceFactorLoss: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var wastepackInfestationChanceFactor: Float # Type C# original: float
