# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_DesignatorDropdownGroupDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var iconSource: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var includeEyeDropperTool: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var useGridMenu: String # Type C# original: string
