# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_DamageDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var additionalHediffs: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var applyAdditionalHediffsIfHuntingForFood: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var armorCategory: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bluntInnerHitChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bluntInnerHitDamageFractionToAdd: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bluntInnerHitDamageFractionToConvert: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bluntStunChancePerDamagePctOfCorePartToBodyCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bluntStunChancePerDamagePctOfCorePartToHeadCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bluntStunDuration: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var buildingDamageFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var buildingDamageFactorImpassable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var buildingDamageFactorPassable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canInterruptJobs: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canUseDeflectMetalEffect: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var causeStun: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var combatLogRules: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var consideredHelpful: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var corpseDamageFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var cutCleaveBonus: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var cutExtraTargetsCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var damageEffecter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var deathMessage: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultArmorPenetration: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultDamage: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultStoppingPower: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var execution: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var explosionAffectOutsidePartsOnly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var explosionCellFleck: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var explosionColorCenter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var explosionColorEdge: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var explosionHeatEnergyPerCell: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var explosionInteriorFleck: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var explosionSnowMeltAmount: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var expolosionPropagationSpeed: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var externalViolence: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var externalViolenceForMechanoids: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var harmAllLayersUntilOutside: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var harmsHealth: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hasForcefulImpact: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hediff: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hediffSkin: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hediffSolid: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var impactSoundType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isExplosive: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var isRanged: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var makesAnimalsFlee: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var makesBlood: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minDamageToFragment: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var overkillPctToDestroyPart: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var plantDamageFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var scaleDamageToBuildingsBasedOnFlammability: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var scratchSplitPercentage: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var soundExplosion: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var stabChanceOfForcedInternal: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var stunAdaptationTicks: Int # Type C# original: int
## Propriété de jeu non documentée sémantiquement.
@export var stunResistStat: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
