# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_DutyDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var alwaysShowWeapon: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var constantThinkNode: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hook: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ritualSpectateTarget: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var socialModeMax: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var thinkNode: String # Type C# original: string
