# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_EffecterDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var children: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maintainTicks: Int # Type C# original: int
## Propriété de jeu non documentée sémantiquement.
@export var offsetTowardsTarget: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var positionRadius: String # Type C# original: string
