# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ExpectationDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var forRoles: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var joyKindsNeeded: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var joyToleranceDropPerDay: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxMapWealth: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var order: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ritualQualityOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var thoughtStage: String # Type C# original: string
