# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ExpansionDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var backgroundPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var iconPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isCore: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var linkedMod: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var notOwnedIconPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var previewImagesFolderPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var primaryColor: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var siteUrl: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var steamUrl: String # Type C# original: string
