# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_FeatureDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var acceptableBiomes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canTouchWorldEdge: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxPassageWidth: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxPctOfWholeArea: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxRootGroupSize: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxSize: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxSpaceBetweenRootGroups: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minRootGroupSize: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minRootGroupsInCluster: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minSize: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var nameMaker: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var order: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var rootBiomes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
