# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_FleckDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var acceleration: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var altitudeLayerIncOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var archCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var archDuration: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var archHeight: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var attachedToHead: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fadeInTime: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fadeOutTime: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fleckSystemClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var graphicData: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var growthRate: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var landSound: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var randomGraphics: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var realTime: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var scalers: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var scalingAnchor: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var solidTime: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var speedPerTime: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var unattachedDrawOffset: String # Type C# original: string
