# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_FactionDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var allowedArrivalTemperatureRange: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var allowedCultures: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var allowedMemes: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var animalsFleeDanger: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var apparelStuffFilter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var arrivalLayerWhitelist: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var autoFlee: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var backstoryFilters: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var baseTraderKinds: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var basicMemberKind: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canSiege: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canStageAttacks: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canUseAvoidGrid: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var caravanTraderKinds: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var categoryTag: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var classicIdeo: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var colorSpectrum: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var configurationListOrderPriority: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disallowedMemes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disallowedPrecepts: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disallowedRaidAgeRestrictions: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var dropPodActive: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var dropPodIncoming: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var earliestRaidDays: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var factionIconPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var factionNameMaker: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fixedLeaderKinds: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fixedName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var forageabilityFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var generateNewLeaderFromMapMembersOnly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hidden: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hostileToFactionlessHumanlikes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var humanlikeFaction: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isPlayer: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var leaderForceGenerateNewPawn: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var leaderTitle: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var listOrderPriority: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxConfigurableAtWorldCreation: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxPawnCostPerTotalPointsCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minSettlementTemperatureChanceCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var mustStartOneEnemy: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pawnGroupMakers: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pawnSingular: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pawnsPlural: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var permanentEnemy: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var permanentEnemyToEveryoneExcept: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var raidCommonalityFromPointsCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var raidLootMaker: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var raidLootValueFromPointsCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var recipePrerequisiteTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredCountAtGameStart: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredMemes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var royalFavorIconPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var royalFavorLabel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var royalTitleInheritanceRelations: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var royalTitleInheritanceWorkerClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var royalTitleTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var settlementGenerationWeight: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var settlementNameMaker: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var settlementTexturePath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var startingCountAtWorldCreation: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var startingResearchTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var startingTechprintsResearchTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var structureMemeWeights: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var techLevel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var xenotypeSet: String # Type C# original: string
