# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_FleshTypeDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var bandagedWounds: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var corpseCategory: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var damageEffecter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var genericWounds: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hediffWounds: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isOrganic: Bool # Type C# original: bool
