# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_GauranlenTreeModeDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var displayedStats: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var drawPosition: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hyperlinks: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pawnKindDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var requiredMemes: String # Type C# original: string
