# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_GameConditionDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var allowUnderground: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canAffectAllPlanetLayers: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canBePermanent: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var conditionClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultDroneLevel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var descriptionFuture: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var endMessage: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var exclusiveConditions: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var jumpToSourceKey: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var letterDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var letterHyperlinks: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var letterText: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var natural: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pennedAnimalsSeekShelter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var preventRain: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var preventShuttleLaunch: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var silencedByConditions: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var weatherDef: String # Type C# original: DefRef
