# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_GatheringDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var calledOffMessage: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var duty: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var finishedMessage: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var gatherSpotDefs: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var letterText: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var letterTitle: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var randomSelectionWeight: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredTitleAny: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var respectTimetable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
