# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_GeneDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var displayOrderInCategory: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hairColorOverride: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minMelanin: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var randomBrightnessFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var selectionWeight: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var selectionWeightCultist: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var selectionWeightFactorDarkSkin: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var skinColorBase: String # Type C# original: string
