# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_GeneCategoryDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var displayPriorityInGenepack: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var displayPriorityInXenotype: String # Type C# original: string
