# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_HistoryAutoRecorderDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var graphColor: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var recordTicksFrequency: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var valueFormat: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
