# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_HediffDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var addedPartProps: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var alwaysShowSeverity: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var battleStateLabel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canApplyDodChanceForCapacityChanges: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var chanceToCauseNoPain: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var chemicalNeed: String # Type C# original: string
## Liste des composants de l'objet, définissant son comportement (ex: CompPowerTrader).
@export var comps: Array # Type C# original: Array
## Propriété de jeu non documentée sémantiquement.
@export var cureAllAtOnceIfCuredByItem: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var debugLabelExtra: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultLabelColor: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var deprioritizeHealing: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var descriptionHyperlinks: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var descriptionShort: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var displayWound: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var duplicationAllowed: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var everCurableByItem: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var forceRenderTreeRecache: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hediffClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hediffGivers: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var initialSeverity: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var injuryProps: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var inspectString: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isBad: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var keepOnBodyPartRestoration: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var labelNoun: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var labelNounPretty: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var lethalSeverity: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var makesSickThought: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxSeverity: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minSeverity: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pregnant: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var preventsCrawling: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var preventsPregnancy: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var priceImpact: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var priceOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var removeOnQuestLodgers: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var removeWithTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var renderNodeProperties: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var scenarioCanAdd: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var skinColorTint: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var skinColorTintStrength: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var spawnThingOnRemoved: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var stages: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var taleOnVisible: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var targetPrefix: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tendable: String # Type C# original: string
