# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_HistoryAutoRecorderGroupDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var devModeOnly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fixedScale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var historyAutoRecorderDefs: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var integersOnly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var onlyPositiveValues: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var useFixedScale: String # Type C# original: string
