# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_HeadTypeDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var eyeOffsetEastWest: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var gender: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var graphicPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var randomChosen: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var selectionWeight: String # Type C# original: string
