# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_IncidentDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var allowedBiomes: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var baseChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var baseChanceWithRoyalty: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canOccurOnAllPlanetLayers: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var category: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disabledWhen: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disallowedBiomes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var diseaseDevelopmentStage: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var diseaseIncident: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var diseaseLethalLetterText: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var diseaseMaxVictims: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var diseasePartsToAffect: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var diseaseVictimFractionRange: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var durationDays: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var earliestDay: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var gameCondition: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ignoreRecentSelectionWeighting: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var letterDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var letterHyperlinkHediffDefs: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var letterLabel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var letterSingularForm: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var letterText: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var mechClusterBuilding: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minGreatestPopulation: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minPopulation: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minRefireDays: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minThreatPoints: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var mtbDaysByBiome: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pawnFixedGender: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pawnKind: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pawnMustBeCapableOfViolence: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pointsScaleable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var populationEffect: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var questScriptDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var refireCheckTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requireColonistsPresent: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var targetTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var treeDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var treeGenStepDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var treeGrowth: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
