# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_IdeoIconDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var cultures: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var iconPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var memes: String # Type C# original: string
