# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_InventoryStockGroupDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultThingDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var thingDefs: Array # Type C# original: Array
