# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_IdeoPresetDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var categoryDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var classicPlus: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var iconPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var memes: String # Type C# original: string
