# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_IncidentCategoryDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var canUseAnomalyChance: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var needsParmsPoints: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tale: String # Type C# original: string
