# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ImpactSoundTypeDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var playOnlyIfHitPawn: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var soundDef: String # Type C# original: DefRef
