# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_InteractionDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ignoreTimeSinceLastInteraction: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var initiatorThought: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var initiatorXpGainAmount: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var initiatorXpGainSkill: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var interactionMote: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var logRulesInitiator: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var recipientThought: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var socialFightBaseChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var symbol: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var symbolSource: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
