# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_InstructionDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var actionTagsAllowed: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var concept: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var endTutorial: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var eventTagInitiate: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var eventTagInitiateSource: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var eventTagsEnd: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var giveOnActivateCount: Int # Type C# original: int
## Propriété de jeu non documentée sémantiquement.
@export var giveOnActivateDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var highlightTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var instructionClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var onMapInstruction: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var recipeDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var recipeTargetCount: Int # Type C# original: int
## Propriété de jeu non documentée sémantiquement.
@export var rejectInputMessage: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var resetBuildDesignatorStuffs: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var startCentered: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var targetCount: Int # Type C# original: int
## Propriété de jeu non documentée sémantiquement.
@export var text: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var textController: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var thingDef: String # Type C# original: DefRef
