# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ImplementOwnerTypeDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var implementOwnerRuleName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var implementOwnerTypeValue: Float # Type C# original: float
