# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_InspirationDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var allowedOnDownedPawns: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var associatedSkills: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var baseDurationDays: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var baseInspectLine: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var beginLetter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var beginLetterDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var endMessage: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minAge: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredAnyNonDisabledWorkType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredAnySkill: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredCapacities: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredNonDisabledStats: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredNonDisabledWorkTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredNonDisabledWorkTypes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredSkills: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var statFactors: Dictionary # Type C# original: Dictionary
## Propriété de jeu non documentée sémantiquement.
@export var statOffsets: String # Type C# original: string
