# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_IdeoStoryPatternDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var noCapitalizeFirstSentence: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var rules: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var segments: String # Type C# original: string
