# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_JobDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var allowOpportunisticPrefix: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var alwaysShowReport: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var alwaysShowWeapon: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var carryThingAfterJob: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var casualInterruptible: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var checkOverrideOnDamage: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var collideWithPawns: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var displayAsAreaInFloatMenu: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var driverClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var dropThingBeforeJob: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ifFlyingKeepFlying: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isCrawlingIfDowned: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var isIdle: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var joyDuration: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var joyKind: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var joyMaxParticipants: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var joySkill: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var joyXpPerTick: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var makeTargetPrisoner: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var neverFleeFromEnemies: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var neverShowWeapon: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var overrideFlyChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var playerInterruptible: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var reportString: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var suspendable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var taleOnCompletion: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tryStartFlying: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var waitAfterArriving: String # Type C# original: string
