# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_jobDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var allowOpportunisticPrefix: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var driverClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var reportString: String # Type C# original: string
