# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_JoyGiverDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var baseChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canDoWhileInBed: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var desireSit: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var giverClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var jobDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var joyKind: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pctPawnsEverDo: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requireChair: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredCapacities: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiresEnjoyOutdoors: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var thingDefs: Array # Type C# original: Array
## Propriété de jeu non documentée sémantiquement.
@export var unroofedOnly: String # Type C# original: string
