# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_KeyBindingCategoryDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var checkForConflicts: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isGameUniversal: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var selfConflicting: String # Type C# original: string
