# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_KeyBindingDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var category: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultKeyCodeA: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultKeyCodeB: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var devModeOnly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var extraConflictTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ignoreConflictsWith: String # Type C# original: string
