# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_LayoutRoomDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var canMergeWithAdjacentRoom: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var edgeTerrain: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var floorTypes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minSingleRectHeight: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minSingleRectWidth: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var prefabs: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var roomContentsWorkerType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var sketchResolverDef: String # Type C# original: DefRef
