# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_LetterDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var arriveSound: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bounce: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var color: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var flashColor: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var flashInterval: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var letterClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pauseMode: String # Type C# original: string
