# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_LifeStageDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var adjective: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var alwaysDowned: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bodyDrawOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bodySizeFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var bodyWidth: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canDoRandomMentalBreaks: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canInitiateSocialInteraction: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canSleepWhenStarving: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canSleepWhileHeld: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canVoluntarilySleep: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var caravanRideable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var claimable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var customMoodTipString: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var developmentalStage: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var equipmentDrawDistanceFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var eyeSizeFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var fallAsleepMaxThresholdOverride: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var foodMaxFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var headSizeFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var healthScaleFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var hungerRateFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var involuntarySleepIsNegativeEvent: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var involuntarySleepMTBDaysFromRest: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var marketValueFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var meleeDamageFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var milkable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var naturalWakeThresholdOverride: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var reproductive: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var shearable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var silhouetteGraphicData: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var sittingOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var statFactors: Dictionary # Type C# original: Dictionary
## Propriété de jeu non documentée sémantiquement.
@export var statOffsets: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var thinkTreeConstantOverride: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var thinkTreeMainOverride: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var visible: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var voxPitch: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var voxVolume: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
