# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_LogEntryDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var iconDamaged: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var iconDamagedFromInstigator: String # Type C# original: string
