# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_MemeDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var addDesignatorGroups: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var addDesignators: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var agreeableTraits: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var allowDuringTutorial: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var allowSymbolsFromDeity: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var apparelRequirements: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var category: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var consumableBuildings: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var deityCount: Int # Type C# original: int
## Propriété de jeu non documentée sémantiquement.
@export var deityNameMakerOverride: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var deityTypeMakerOverride: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var descriptionMaker: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disagreeableTraits: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var exclusionTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fixedDeityNameTypes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var generalRules: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var groupDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var iconPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var impact: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var preferredWeaponClasses: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var preventApparelRequirements: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var randomizationSelectionWeightFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var renderOrder: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var replaceRitualsWithTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var replacementPatterns: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requireAnyRitualSeat: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requireOne: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredRituals: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ritualsToMake: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var selectOneOrNone: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var startingResearchProjects: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var styleItemTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var symbolPackOverride: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var symbolPacks: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var thingStyleCategories: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var veneratedAnimalsCountOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var veneratedAnimalsCountOverride: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var worshipRoomLabel: String # Type C# original: string
