# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_MentalBreakDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var baseCommonality: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var commonalityFactorPerPopulationCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var intensity: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var layerWhitelist: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var mentalState: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var questLodgersCanDo: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredTrait: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
