# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_MeditationFocusDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var incompatibleBackstoriesAny: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredBackstoriesAny: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiresRoyalTitle: String # Type C# original: string
