# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ManeuverDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var combatLogRulesDeflect: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var combatLogRulesDodge: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var combatLogRulesHit: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var combatLogRulesMiss: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var logEntryDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var requiredCapacity: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var verb: String # Type C# original: string
