# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_MainButtonDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var buttonVisible: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canBeTutorDenied: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var closesWorldView: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultHotKey: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var iconPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minimized: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var order: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tabWindowClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var validWithClassicIdeo: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var validWithoutMap: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
