# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_MentalStateDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var allowBeatfire: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var allowGuilty: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var baseInspectLine: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var beginLetter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var beginLetterDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var beginLetterLabel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var blockInteractionInitiationExcept: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var blockInteractionRecipientExcept: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var blockNormalThoughts: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var blockRandomInteraction: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var category: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var colonistsOnly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var drugCategory: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var escapingPrisonersIgnore: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ignoreDrugPolicy: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var inCaravanCanDo: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxTicksBeforeRecovery: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minTicksBeforeRecovery: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var moodRecoveryThought: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var nameColor: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var prisonersCanDo: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var recoverFromCollapsingExhausted: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var recoverFromDowned: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var recoverFromSleep: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var recoveryMessage: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var recoveryMtbDays: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredCapacities: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var slavesCanDo: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var slavesOnly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var stateClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var stateEffecter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
