# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_MechWeightClassDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var canResurrect: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
