# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_MemeGroupDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var drawOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxRows: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var renderOrder: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var renderWithGap: String # Type C# original: string
