# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_NeedDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var baseLevel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var colonistAndPrisonersOnly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var colonistsOnly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var developmentalStageFilter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fallPerDay: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var freezeInMentalState: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var freezeWhileSleeping: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var listPriority: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var major: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minIntelligence: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var needClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var neverOnPrisoner: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var neverOnSlave: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var nullifyingPrecepts: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var onlyIfCausedByGene: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var onlyIfCausedByHediff: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var onlyIfCausedByIdeo: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var onlyIfCausedByTrait: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var seekerFallPerHour: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var seekerRisePerHour: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showForCaravanMembers: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showOnNeedList: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showUnitTicks: Int # Type C# original: int
## Propriété de jeu non documentée sémantiquement.
@export var slavesOnly: String # Type C# original: string
