# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_PrisonerInteractionModeDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var allowInClassicIdeoMode: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var allowOnWildMan: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hideIfNotRecruitable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isChildInteraction: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var listOrder: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var mustBeAwake: String # Type C# original: string
