# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_PawnRelationDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var diedThought: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var diedThoughtFemale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var familyByBloodRelation: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var generationChanceFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var implied: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var importance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var inbredChanceOnChild: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var incestOpinionOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var killedThought: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var killedThoughtFemale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var labelFemale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var lostThought: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var lostThoughtFemale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var opinionOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var reflexive: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var romanceChanceFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var soldThoughts: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
