# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_PlaceDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var placeRules: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tags: String # Type C# original: string
