# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_PawnsArrivalModeDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var layerWhitelist: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minTechLevel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pointsFactorCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var selectionWeightCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var selectionWeightCurvesPerFaction: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var textEnemy: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var textFriendly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var textWillArrive: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var walkIn: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
