# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_PreceptDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var abilityStatFactors: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var allowDuplicates: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var allowOptionalRitualObligations: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var apparelPreceptSwapDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var approvesOfBlindness: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var approvesOfCharity: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var approvesOfSlavery: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var associatedMemes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var biosculpterPodCycleSpeedFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var blindPawnChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var blindPsychicSensitivityOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var buildingDefChances: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var buildingMinExpectations: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var buildingRoomRequirements: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var buildingRoomRequirementsFixed: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canGenerateAsSpecialPrecept: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canRemoveInUI: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canUseAlreadyUsedThingDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var capitalizeAsTitle: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var classic: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var classicExtra: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var classicModeOnly: String # Type C# original: string
## Liste des composants de l'objet, définissant son comportement (ex: CompPowerTrader).
@export var comps: Array # Type C# original: Array
## Propriété de jeu non documentée sémantiquement.
@export var conflictingMemes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var convertPowerFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var countsTowardsPreceptLimit: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultDrugPolicyOverride: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultSelectionWeight: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disablesNeeds: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disallowFarmingCamps: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disallowHuntingCamps: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disallowLoggingCamps: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disallowMiningCamps: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var displayOrderInImpact: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var displayOrderInIssue: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var enabledForNPCFactions: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var enablesNeeds: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var exclusionTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var expectationsOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var extraTextPawnDeathLetter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var genderPrefersNudity: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var grantedAbilities: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var iconIgnoresIdeoColor: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var iconPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ignoreLimitsInEditMode: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ignoreNameUniqueness: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var impact: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var issue: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var leaderRole: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var likesHumanLeatherApparel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var listedForRoles: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxCount: Int # Type C# original: int
## Propriété de jeu non documentée sémantiquement.
@export var mergeRitualGizmosFromAllIdeos: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var nameMaker: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var notifyPlayerOnOpportunity: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var opposedWorkTypes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var preceptClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var preceptInstanceCountCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var prefersDarkness: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var prefersNudity: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var prefersSlabBed: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var receivesExpectationsQualityOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredMemes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredScars: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var restrictToSupremeGenderChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ritualPatternBase: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var roleApparelRequirementCountCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var roleApparelRequirements: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var roleDisabledWorkTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var roleEffects: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var roleRequiredWorkTagAny: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var roleRequiredWorkTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var roleRequirements: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var roleTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var roomRequirementCountCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var selectionWeight: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showRitualFloatMenuOption: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var sourceAbilityDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var sourcePawnRoleDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var statFactors: Dictionary # Type C# original: Dictionary
## Propriété de jeu non documentée sémantiquement.
@export var statOffsets: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var takeNameFrom: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tipLabelOverride: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var useChoicesFromBuildingDefs: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var useCooldownFromAbilityGroupDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var useRepeatPenalty: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var usesIdeoVisualEffects: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var visible: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var warnPlayerOnDesignateChopTree: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var warnPlayerOnDesignateMine: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var willingToConstructOtherIdeoBuildables: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
