# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_PawnKindDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var abilities: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var acceptArrestChanceFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var allowRoyalApparelRequirements: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var allowRoyalRoomRequirements: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var alternateGraphicChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var alternateGraphics: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var apparelAllowHeadgearChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var apparelColor: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var apparelDisallowTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var apparelIgnorePollution: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var apparelIgnoreSeasons: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var apparelMoney: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var apparelRequired: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var apparelTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var backstoryCryptosleepCommonality: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var backstoryFilters: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var backstoryFiltersOverride: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var biocodeWeaponChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canArriveManhunter: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canBeSapper: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var chemicalAddictionChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var combatEnhancingDrugsChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var combatEnhancingDrugsCount: Int # Type C# original: int
## Propriété de jeu non documentée sémantiquement.
@export var combatPower: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultFactionDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var defendPointRadius: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disallowedTraits: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ecoSystemWeight: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var factionHostileOnDeath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var factionLeader: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var favoriteColor: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var flyingAnimationDrawSize: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var flyingAnimationDrawSizeIsMultiplier: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var flyingAnimationFrameCount: Int # Type C# original: int
## Propriété de jeu non documentée sémantiquement.
@export var flyingAnimationFramePathPrefix: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var flyingAnimationFramePathPrefixFemale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var flyingAnimationInheritColors: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var flyingAnimationTicksPerFrame: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var forceNormalGearQuality: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var gearHealthRange: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var humanPregnancyChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ignoreIdeoApparelColors: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var initialResistanceRange: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var initialWillRange: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var invFoodDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var invNutrition: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var inventoryOptions: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isFighter: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var isGoodBreacher: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var itemQuality: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var labelFemale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var labelFemalePlural: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var labelMale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var labelPlural: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var lifeStages: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxGenerationAge: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minGenerationAge: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minTitleRequired: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var race: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredWorkTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var royalTitleChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var skills: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var specificApparelRequirements: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var styleItemTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var techHediffsChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var techHediffsDisallowTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var techHediffsMaxAmount: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var techHediffsMoney: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var techHediffsRequired: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var techHediffsTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var titleRequired: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var titleSelectOne: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var trader: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var useFactionXenotypes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var weaponMoney: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var weaponTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var wildGroupSize: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var xenotypeSet: String # Type C# original: string
