# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_PawnColumnDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var gap: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var headerIcon: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var headerTip: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ignoreWhenCalculatingOptimalTableSize: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var paintable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showIcon: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var sortable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var useLabelShort: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var width: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var widthPriority: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
