# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_PlanetLayerDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var backgroundBiome: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var elevationString: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var gerundLabel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var layerType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tileType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var viewGizmoTexPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var viewGizmoTooltip: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var worldDrawLayers: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var worldGenSteps: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var worldTabs: String # Type C# original: string
