# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_PrefabDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var edgeOnly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var rotations: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var size: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var things: String # Type C# original: string
