# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_PathGridDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fencePassable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var flying: String # Type C# original: string
