# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_PawnCapacityDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var labelAnomalyEntity: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var labelDrones: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var labelMechanoids: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var lethalFlesh: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var lethalMechanoids: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var listOrder: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minForCapable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minValue: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var showOnAnimals: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showOnAnomalyEntities: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showOnCaravanHealthTab: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showOnDrones: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showOnMechanoids: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var zeroIfCannotBeAwake: String # Type C# original: string
