# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_QuestScriptDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var affectedByPoints: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var affectedByPopulation: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var autoAccept: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canGiveRoyalFavor: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultChallengeRating: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultCharity: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultHidden: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var endOnColonyMove: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var epic: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var epicParent: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var everAcceptableInSpace: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var expireDaysRange: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var failedOrExpiredHistoryEvent: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hideInvolvedFactionsInfo: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isRootSpecial: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var questAvailableLetterDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var questContentRules: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var questDescriptionAndNameRules: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var questDescriptionRules: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var questNameRules: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var root: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var rootIncreasesPopulation: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var rootMinPoints: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var rootMinProgressScore: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var rootSelectionWeight: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var rootSelectionWeightFactorFromPointsCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var sendAvailableLetter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var successHistoryEvent: String # Type C# original: string
