# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_RoyalTitleDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var allowDignifiedMeditationFocus: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var awardWorkerClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bedroomRequirements: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canBeInherited: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var changeHeirQuestPoints: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var commonality: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var decreeMentalBreakCommonality: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var decreeMtbDays: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var decreeTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disabledJoyKinds: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disabledWorkTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var favorCost: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var foodRequirement: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var grantedAbilities: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var labelFemale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxPsylinkLevel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minExpectation: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var permitPointsAwarded: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var permits: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var recruitmentResistanceOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var replaceOnRecruited: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredApparel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredMinimumApparelQuality: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var seniority: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var speechCooldown: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var suppressIdleAlert: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var throneRoomRequirements: String # Type C# original: string
