# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_RitualBehaviorDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var cancellationTriggers: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var durationTicks: Int # Type C# original: int
## Propriété de jeu non documentée sémantiquement.
@export var letterText: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var letterTitle: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxEnhancerDistance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var preceptRequirements: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var roles: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var soundDefsPerEnhancerCount: Int # Type C# original: int
## Propriété de jeu non documentée sémantiquement.
@export var spectatorFilter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var spectatorGerund: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var spectatorsLabel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var stages: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var useVisualEffectsFromRoleIdIdeo: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
