# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_RitualPatternDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var alwaysStartAnytime: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canMergeGizmosFromDifferentIdeos: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canStartAnytime: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var descOverride: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var iconPathOverride: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ignoreConsumableBuildingRequirement: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var layerBlacklist: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxTechLevel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var mergeGizmosForObligations: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minTechLevel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var nameMaker: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var patternGroupTag: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var playsIdeoMusic: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ritualBehavior: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ritualExpectedDesc: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ritualExpectedDescNoAdjective: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ritualExplanation: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ritualObligationTargetFilter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ritualObligationTriggers: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ritualOnlyForIdeoMembers: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ritualOutcomeEffect: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ritualTargetFilter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var shortDescOverride: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tags: String # Type C# original: string
