# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_RitualObligationTargetFilterDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxDrumDistance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxSpeakerDistance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minUnroofedCells: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var thingDefs: Array # Type C# original: Array
## Propriété de jeu non documentée sémantiquement.
@export var unroofedCellSearchRadius: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var woodPerParticipant: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
