# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_RitualOutcomeEffectDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var allowAttachableOutcome: Bool # Type C# original: bool
## Liste des composants de l'objet, définissant son comportement (ex: CompPowerTrader).
@export var comps: Array # Type C# original: Array
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var effecter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var extraInfoLines: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var extraPredictedOutcomeDescriptions: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var filthCountToSpawn: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var filthDefToSpawn: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fleckDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var fleckScaleRange: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fleckVelocityAngle: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fleckVelocitySpeed: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var flecksPerCell: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var givesDevelopmentPoints: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var honorFromQuality: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxQuality: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minQuality: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var outcomeChances: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var startingQuality: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var warnOnLowQuality: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
