# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_RecordDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var displayOrder: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var measuredTimeJobs: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var type: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
