# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ResearchTabDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var generalDescription: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var generalTitle: String # Type C# original: string
