# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_RiverDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var branches: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var debugOpacity: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var degradeChild: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var degradeThreshold: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var spawnChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var spawnFlowThreshold: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var widthOnMap: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var widthOnWorld: String # Type C# original: string
