# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_RoadDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var ancientOnly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var distortionFrequency: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var distortionIntensity: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var movementCostMultiplier: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pathingMode: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var priority: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var roadGenSteps: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tilesPerSegment: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var worldRenderSteps: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var worldTransitionGroup: String # Type C# original: string
