# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_RaidStrategyDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var arrivalTextEnemy: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var arrivalTextFriendly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var arriveModes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var layerWhitelist: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var letterLabelEnemy: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var letterLabelFriendly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minPawns: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pawnsCanBringFood: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pointsFactorCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var raidLootValueFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var selectionWeightCurvesPerFaction: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var selectionWeightPerPointsCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
