# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_RoyalTitlePermitDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var cooldownDays: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var faction: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var layerBlacklist: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minTitle: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var permitPointCost: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var prerequisite: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var royalAid: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var uiPosition: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var usableOnWorldMap: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
