# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ResearchProjectDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var baseCost: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var discoveredLetterDisabledWhen: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var discoveredLetterText: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var discoveredLetterTitle: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var generalRules: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var heldByFactionCategoryTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hiddenPrerequisites: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hideWhen: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var prerequisites: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var recalculatePower: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredResearchBuilding: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredResearchFacilities: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var researchViewX: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var researchViewY: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var techLevel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var techprintCommonality: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var techprintCount: Int # Type C# original: int
## Propriété de jeu non documentée sémantiquement.
@export var techprintMarketValue: Float # Type C# original: float
