# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_RitualAttachableOutcomeEffectDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disallowedRituals: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var effectDesc: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var letterInfoText: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredFaction: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredMemeAny: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
