# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_RecipeDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var addsHediff: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var allowMixingIngredients: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var anesthetize: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var appliedOnFixedBodyPartGroups: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var appliedOnFixedBodyParts: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var autoStripCorpses: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var conceptLearned: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var deathOnFailedSurgeryChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultIngredientFilter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var descriptionHyperlinks: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var developmentalStageFilter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var displayPriority: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var dontShowIfAnyIngredientMissing: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var effectWorking: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var efficiencyStat: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fixedIngredientFilter: Array # Type C# original: Array
## Propriété de jeu non documentée sémantiquement.
@export var forceHiddenSpecialFilters: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hideBodyPartNames: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ignoreIngredientCountTakeEntireStacks: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var incompatibleWithHediffTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ingredientValueGetterClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ingredients: Array # Type C# original: Array
## Propriété de jeu non documentée sémantiquement.
@export var interruptIfIngredientIsRotting: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isViolation: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var jobString: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var products: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var recipeUsers: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var removesHediff: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredGiverWorkType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var researchPrerequisite: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var skillRequirements: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var smeltingWorkAmount: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var soundWorking: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var specialProducts: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var successfullyRemovedHediffMessage: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var surgeryIgnoreEnvironment: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var surgeryOutcomeEffect: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var surgerySuccessChanceFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var targetCountAdjustment: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var targetsBodyPart: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var uiIconThing: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var unfinishedThingDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var workAmount: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workSkill: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workSpeedStat: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerCounterClass: String # Type C# original: string
