# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_RuleDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var resolvers: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var symbol: String # Type C# original: string
