# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_RoofDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var collapseLeavingThingDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var filthLeaving: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isNatural: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var isThickRoof: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var soundPunchThrough: String # Type C# original: string
