# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_RoomStatDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var curve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var displayRounded: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var inputStat: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isHidden: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var roomlessScore: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var scoreStages: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var updatePriority: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
