# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ShaderTypeDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var shaderPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var uiShaderPath: String # Type C# original: string
