# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_StorytellerDef extends CR_Base

## Liste des composants de l'objet, définissant son comportement (ex: CompPowerTrader).
@export var comps: Array # Type C# original: Array
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disableAdaptiveTraining: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disableAlerts: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disablePermadeath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var forcedDifficulty: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var listOrder: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var listVisible: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var populationIntentFactorFromPopCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var portraitLarge: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var portraitTiny: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tutorialMode: String # Type C# original: string
