# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_SketchResolverDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isRoot: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var resolver: String # Type C# original: string
