# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_SoundDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var context: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxSimultaneous: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxVoices: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var priorityMode: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var slot: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var subSounds: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var sustain: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var sustainFadeoutTime: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var sustainStartSound: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var sustainStopSound: String # Type C# original: string
