# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_SongDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var clipPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var playOnMap: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var volume: String # Type C# original: string
