# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_StyleCategoryDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var addDesignatorGroups: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var addDesignators: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var iconPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ritualVisualEffectDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var soundOngoingRitual: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var thingDefStyles: String # Type C# original: string
