# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_SitePartDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var activeThreatDisturbanceFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var applyFactionColorToSiteTexture: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var approachOrderString: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var approachingReportString: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var arrivedLetter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var arrivedLetterDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var arrivedLetterHediffHyperlinks: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var badEvenIfNoMap: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var conditionCauserDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var considerEnteringAsAttack: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultHidden: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disallowsAutomaticDetectionTimerStart: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var excludesTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var expandingIconTexture: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var forceExitAndRemoveMapCountdownDurationDays: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var gravShipsCanLandOn: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var handlesWorldObjectTimeoutInspectString: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ignoreIllegalLabelCharacterConfigError: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var increasesPopulation: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var lootTable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var mainPartAllThreatsLabel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minFactionTechLevel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minMapSize: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minThreatPoints: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiresFaction: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var selectionWeight: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showFactionInInspectString: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var siteTexture: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var wantsThreatPoints: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
