# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ShipJobDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var blocksDisposalIfQueuedUnspawned: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var jobClass: String # Type C# original: string
