# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ScatterableDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var scatterType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var texturePath: String # Type C# original: string
