# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_SkillDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disablingWorkTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var generalRules: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var lessonInteraction: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var listOrder: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var neverDisabledBasedOnWorkTypes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pawnCreatorSummaryVisible: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var skillLabel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var usuallyDefinedInBackstories: String # Type C# original: string
