# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_StatDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var alwaysHide: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var applyFactorsIfNegative: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var cacheable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var capacityFactors: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var capacityOffsets: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var category: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultBaseValue: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var disableIfSkillDisabled: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var displayMaxWhenAboveOrEqual: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var displayPriorityInCategory: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var finalizeEquippedStatOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var forInformationOnly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var formatString: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var formatStringUnfinalized: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hideAtValue: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var hideInClassicMode: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var labelForFullStatList: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxValue: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var minValue: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var minifiedThingInherits: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var neverDisabled: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var noSkillOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var parts: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var postProcessCurve: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var postProcessStatFactors: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var roundToFiveOver: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var roundValue: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var scenarioRandomizable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showDevelopmentalStageFilter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showIfHediffsPresent: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showIfModsLoaded: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showIfModsLoadedAny: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showIfUndefined: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showNonAbstract: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showOnAnimals: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showOnDefaultValue: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var showOnDrones: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showOnEntities: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showOnMechanoids: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showOnNonPowerPlants: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showOnNonWildManHumanlikes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showOnNonWorkTables: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showOnPawnKind: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showOnPawns: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showOnPlayerMechanoids: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showOnSlavesOnly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showOnUnhaulables: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showOnUntradeables: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showZeroBaseValue: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var skillNeedFactors: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var skillNeedOffsets: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var statFactors: Dictionary # Type C# original: Dictionary
## Propriété de jeu non documentée sémantiquement.
@export var supressDisabledError: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var toStringStyle: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var toStringStyleUnfinalized: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var valueIfMissing: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
