# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ScenPartDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var canBePlayerAddedRemoved: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canBeRandomlyAdded: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var category: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var designatorType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var durationRandomRange: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var gameCondition: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var gameConditionTargetsWorld: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxUses: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pageClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var scenPartClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var selectionWeight: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var summaryPriority: String # Type C# original: string
