# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_StuffCategoryDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var destroySoundLarge: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var destroySoundMedium: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var destroySoundSmall: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var noun: String # Type C# original: string
