# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_SpecialThingFilterDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var allowedByDefault: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var configurable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var parentCategory: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var saveKey: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
