# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_SubcameraDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var depth: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var format: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var layer: String # Type C# original: string
