# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ThingSetMakerDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var debugParams: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var root: String # Type C# original: string
