# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_TerrainAffordanceDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var affordanceOverlayColor: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var blockAffordanceOverlay: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var order: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var visualizeOnAffordanceOverlay: String # Type C# original: string
