# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ThoughtDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var developmentalStageFilter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var doNotApplyToQuestLodgers: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var durationDays: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var effectMultiplyingStat: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var gameCondition: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var gender: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hediff: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var icon: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var invert: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxCumulatedOpinionOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minExpectation: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minExpectationForNegativeThought: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var neverNullifyIfAnyTrait: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var nextThought: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var nullifiedIfNotColonist: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var nullifyingGenes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var nullifyingHediffs: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var nullifyingOwnTales: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var nullifyingPrecepts: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var nullifyingTraitDegrees: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var nullifyingTraits: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var producesMemoryThought: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var replaceThoughts: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredTraits: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredTraitsDegree: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var showBubble: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var socialTargetDevelopmentalStageFilter: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var stackLimit: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var stackLimitForSameOtherPawn: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var stackedEffectMultiplier: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var stages: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var stagesStack: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var taleDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var thoughtClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var thoughtToMake: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var validWhileDespawned: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
