# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_TrainableDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultTrainable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var difficulty: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var icon: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var listPriority: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minBodySize: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var prerequisites: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredTrainability: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var steps: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tags: String # Type C# original: string
