# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ThingDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var allowedArchonexusCount: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var alwaysFlee: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var alwaysHaulable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var apparel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var blockLight: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var blockPlants: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var blockWeather: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var blockWind: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bringAlongOnGravship: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var building: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var burnableByRecipe: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var butcherProducts: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canBeUsedUnderRoof: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canEditAnyStyle: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canGenerateDefaultDesignator: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canInteractThroughCorners: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canLoadIntoCaravan: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canOverlapZones: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canScatterOver: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var castEdgeShadows: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var category: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var clearBuildingArea: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var colorGenerator: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var colorGeneratorInTraderStock: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var colorPerStuff: String # Type C# original: string
## Liste des composants de l'objet, définissant son comportement (ex: CompPowerTrader).
@export var comps: Array # Type C# original: Array
## Propriété de jeu non documentée sémantiquement.
@export var constructEffect: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var constructionSkillPrerequisite: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var containedItemsSelectable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var containedPawnsSelectable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var costList: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var costListForDifficulty: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var costStuffCount: Int # Type C# original: int
## Propriété de jeu non documentée sémantiquement.
@export var coversFloor: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var damageMultipliers: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var deepCommonality: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var deepCountPerPortion: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var deepLumpSizeRange: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defaultPlacingRot: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var descriptionHyperlinks: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var designationCategory: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var designationHotKey: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var destroyOnDrop: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var destroyable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var devNote: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var displayNumbersBetweenSameDefDistRange: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var dominantStyleCategory: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var dontPrint: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var drawDamagedOverlay: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var drawGUIOverlay: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var drawHighlight: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var drawHighlightOnlyForHostile: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var drawOffscreen: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var drawPlaceWorkersWhileInstallBlueprintSelected: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var drawPlaceWorkersWhileSelected: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var drawStyleCategory: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var drawerType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var equipmentType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var equippedAngleOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var equippedStatOffsets: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fertility: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fillPercent: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var filth: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var filthLeaving: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var forceDebugSpawnable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var generateAllowChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var generateCommonality: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var graphicData: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hasCustomRectForSelector: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hasInteractionCell: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hasTooltip: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var healthAffectsPrice: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hideAtSnowOrSandDepth: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hideInspect: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var highlightColor: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var holdsRoof: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ideoBuildingNamerBase: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ingestible: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ingredient: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var inspectorTabs: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var interactionCellIcon: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var interactionCellIconReverse: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var interactionCellOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var intricate: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isAltar: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var isMechClusterThreat: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var isTechHediff: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var killedLeavings: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var leaveResourcesWhenKilled: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxTechLevelToBuild: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var meleeHitSound: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minRewardCount: Int # Type C# original: int
## Propriété de jeu non documentée sémantiquement.
@export var minTechLevelToBuild: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minifiedDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var minifiedDrawOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var minifiedDrawScale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var mote: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var neverMultiSelect: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var neverOverlapFloors: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var noRightClickDraftAttack: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var notifyMapRemoved: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var overrideMinifiedRot: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var passability: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pathCost: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var pathCostIgnoreRepeat: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pathfinderDangerous: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pawnFlyer: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var placeWorkers: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var plant: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var possessionCount: Int # Type C# original: int
## Propriété de jeu non documentée sémantiquement.
@export var preventDroppingThingsOn: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var preventSkyfallersLandingOn: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var projectile: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var projectileWhenLoaded: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var race: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var randomStyle: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var randomStyleChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var receivesSignals: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var recipeMaker: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var recipes: Array # Type C# original: Array
## Propriété de jeu non documentée sémantiquement.
@export var recoilPower: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var relicChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var repairEffect: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var replaceTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiresFactionToAcquire: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var researchPrerequisites: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var resourceReadoutAlwaysShow: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var resourceReadoutPriority: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var resourcesFractionWhenDeconstructed: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ritualFocus: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var rotatable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var rotateInShelves: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var saveCompressible: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var scatterableOnMapGen: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var seeThroughFog: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var selectable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var size: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var skyfaller: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var slagDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var smallVolume: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var smeltProducts: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var smeltable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var socialPropernessMatters: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var soundDrop: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var soundImpactDefault: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var soundInteract: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var soundOpen: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var soundPlayInstrument: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var specialDisplayRadius: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var stackLimit: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var startingHpRange: String # Type C# original: string
## Dictionnaire des statistiques de base de l'objet/entité.
@export var statBases: Dictionary # Type C# original: Dictionary
## Propriété de jeu non documentée sémantiquement.
@export var staticSunShadowHeight: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var stealable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var stuffCategories: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var stuffProps: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var surfaceType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var techHediffsTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var techLevel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var terrainAffordanceNeeded: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var thingCategories: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var thingClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var thingSetMakerTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tickerType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tools: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tradeNeverStack: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tradeTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tradeability: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var uiIconOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var uiIconPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var uiIconPathsStuff: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var uiIconScale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var uiOrder: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var useBlueprintGraphicAsGhost: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var useHitPoints: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var useSameGraphicForGhost: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var useStuffTerrainAffordance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var verbs: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var violentTechHediff: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var weaponClasses: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var weaponTags: String # Type C# original: string
