# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_TraitDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var allowOnHostileSpawn: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var commonality: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var commonalityFemale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var conflictingPassions: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var conflictingTraits: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var degreeDatas: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disabledWorkTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var exclusionTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var forcedPassions: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredWorkTags: String # Type C# original: string
