# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_TransportShipDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var arrivingSkyfaller: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var leavingSkyfaller: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxLaunchDistance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var shipThing: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var worldObject: String # Type C# original: string
