# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_TraderKindDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var category: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var commonality: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var commonalityMultFromPopulationIntent: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var faction: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var hideThingsNotWillingToTrade: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var orbital: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var permitRequiredForTrading: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requestable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var stockGenerators: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tradeCurrency: String # Type C# original: string
