# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_TerrainTemplateDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var burnedDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var constructionSkillPrerequisite: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var costList: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var designatorDropdown: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var dominantStyleCategory: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ignoreIllegalLabelCharacterConfigError: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var renderPrecedenceStart: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var researchPrerequisites: String # Type C# original: string
## Dictionnaire des statistiques de base de l'objet/entité.
@export var statBases: Dictionary # Type C# original: Dictionary
## Propriété de jeu non documentée sémantiquement.
@export var tags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var texturePath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var uiOrder: String # Type C# original: string
