# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_TattooDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var category: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var iconPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var noGraphic: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var styleTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tattooType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var texPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var visibleNorth: String # Type C# original: string
