# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_TimeAssignmentDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var allowJoy: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var allowRest: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var color: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
