# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ThingCategoryDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var iconPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var parent: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var resourceReadoutRoot: String # Type C# original: string
