# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_TerrainDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var affordances: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var avoidWander: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bridgePropsPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var burnedDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var canEverTerraform: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canFreeze: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canGenerateDefaultDesignator: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var categoryType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var color: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var constructEffect: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var constructionSkillPrerequisite: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var costList: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var designationCategory: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var designationHotKey: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var designatorDropdown: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var destroyOnBombDamageThreshold: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var dominantStyleCategory: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var drawStyleCategory: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var driesTo: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var edgeType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var extinguishesFire: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fertility: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var floodTerrain: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var forcePassableByFlyingPawns: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var generatedFilth: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var gravshipReplacementTerrain: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isPaintable: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var layerable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pathCost: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var placeWorkers: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pollutedTexturePath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pollutionCloudColor: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pollutionColor: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pollutionOverlayScale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pollutionOverlayScrollSpeed: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pollutionOverlayTexturePath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pollutionShaderType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pollutionTintColor: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var renderPrecedence: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var researchPrerequisites: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var resourcesFractionWhenDeconstructed: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var scatterType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var spaceEdgeGraphicData: String # Type C# original: string
## Dictionnaire des statistiques de base de l'objet/entité.
@export var statBases: Dictionary # Type C# original: Dictionary
## Propriété de jeu non documentée sémantiquement.
@export var tags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var takeFootprints: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var texturePath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var tools: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var uiIconPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var uiOrder: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var waterBodyType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var waterDepthShader: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var waterDepthShaderParameters: String # Type C# original: string
