# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_TileMutatorDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var categories: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var genOrder: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var priority: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
