# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_TaleDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var baseInterest: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var colonistOnly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defSymbol: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var expireDays: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var firstPawnSymbol: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var historyGraphColor: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ignoreChance: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var maxPerPawn: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var rulePack: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var secondPawnSymbol: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var taleClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var type: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var usableForArt: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var usableWithChildren: String # Type C# original: string
