# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_ThingStyleDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var graphicData: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var overrideLabel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var uiIconPath: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var uiIconScale: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var wornGraphicPath: String # Type C# original: string
