# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_WorkGiverDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var autoTakeablePriorityDrafted: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var billGiversAllAnimals: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var billGiversAllAnimalsCorpses: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var billGiversAllHumanlikes: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var billGiversAllHumanlikesCorpses: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canBeDoneByMechs: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canBeDoneWhileDrafted: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var directOrderable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var doesSmoothing: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var emergency: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var equivalenceGroup: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var feedAnimalsOnly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var feedHumanlikesOnly: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fixedBillGiverDefs: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var forceFleck: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var gerund: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var giverClass: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var nonColonistsCanDo: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var prioritizeSustains: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var priorityInType: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requiredCapacities: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var scanCells: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var scanThings: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var scannerDef: String # Type C# original: DefRef
## Propriété de jeu non documentée sémantiquement.
@export var tagToGive: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var verb: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workType: String # Type C# original: string
