# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_WeaponTraitDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var bondedHediffs: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var bondedThought: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var commonality: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var equippedHediffs: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var equippedStatOffsets: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var exclusionTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var killThought: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var marketValueOffset: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var neverBond: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workerClass: String # Type C# original: string
