# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_WorkTypeDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var alwaysStartActive: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var disabledForSlaves: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var gerundLabel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var labelShort: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var naturalPriority: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var pawnLabel: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var relevantSkills: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var requireCapableColonist: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var verb: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var workTags: String # Type C# original: string
