# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_WeatherDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var accuracyMultiplier: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var ambientSounds: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var commonalityRainfallFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var durationRange: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var eventMakers: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var favorability: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isBad: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var moveSpeedMultiplier: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var overlayClasses: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var perceivePriority: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var rainRate: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var repeatable: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var skyColorsDay: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var skyColorsDusk: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var skyColorsNightEdge: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var skyColorsNightMid: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var snowRate: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var temperatureRange: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var weatherThought: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var windSpeedFactor: Float # Type C# original: float
## Propriété de jeu non documentée sémantiquement.
@export var windSpeedOffset: String # Type C# original: string
