# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_WorldObjectDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var IncidentTargetTags: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var allowCaravanIncidentsWhichGenerateMap: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var blockExitGridUntilBattleIsWon: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var canBePlayerHome: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var canHaveMap: Bool # Type C# original: bool
## Liste des composants de l'objet, définissant son comportement (ex: CompPowerTrader).
@export var comps: Array # Type C# original: Array
## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var expandMore: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var expandingIcon: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var expandingIconDrawSize: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var expandingIconPriority: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var expandingIconTexture: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var fullyExpandedInSpace: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var inspectorTabs: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var isTempIncidentMapOwner: Bool # Type C# original: bool
## Propriété de jeu non documentée sémantiquement.
@export var mapGenerator: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var overrideMapSize: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var saved: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var texture: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var useDynamicDrawer: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var validLaunchTarget: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var worldObjectClass: String # Type C# original: string
