# Autogenerated by MFD-VCS Pipeline - DO NOT EDIT MANUALLY
class_name CR_WeaponClassPairDef extends CR_Base

## Propriété de jeu non documentée sémantiquement.
@export var defName: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var first: String # Type C# original: string
## Propriété de jeu non documentée sémantiquement.
@export var second: String # Type C# original: string
